export const SET_USER = 'SET_USER'

export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const LOGIN_USER = 'LOGIN_USER'
export const APPROVE_USER = 'APPROVE_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const LOGOUT_USER = 'LOGOUT_USER'

export const CLEAR_USER_ERROR = 'CLEAR_USER_ERROR'

export const CLEAR_USER = 'CLEAR_USER'

export const SET_STUDENTS = 'SET_STUDENTS'
export const SET_STUDENTS_LOADING = 'SET_STUDENTS_LOADING'
export const SET_STUDENTS_ERRORS = 'SET_STUDENTS_ERRORS'

export const REMOVE_STUDENT = 'REMOVE_STUDENT'
export const APPROVE_STUDENT = 'APPROVE_STUDENT'
export const DISAPPROVE_STUDENT = 'DISAPPROVE_STUDENT'

export const REMOVE_STUDENTS = 'REMOVE_STUDENTS'
export const APPROVE_STUDENTS = 'APPROVE_STUDENTS'
export const DISAPPROVE_STUDENTS = 'DISAPPROVE_STUDENTS'

export const ADD_INSTALLMENT = 'ADD_INSTALLMENT'
export const REMOVE_INSTALLMENT = 'REMOVE_INSTALLMENT'
export const SET_INSTALLMENTS = 'SET_INSTALLMENTS'

export const SET_INSTALLMENTS_LOADING = 'SET_INSTALLMENTS_LOADING'
export const SET_INSTALLMENTS_ERRORS = 'SET_INSTALLMENTS_ERRORS'

export const ADD_USERS = 'ADD_USERS'
export const REMOVE_USERS = 'REMOVE_USERS'
export const SET_USERS = 'SET_USERS'

export const SET_USERS_LOADING = 'SET_USERS_LOADING'
export const SET_USERS_ERRORS = 'SET_USERS_ERRORS'

export const SET_APPLICATION = 'SET_APPLICATION'
export const SET_APPLICATION_STATUS = 'SET_APPLICATION_STATUS'
export const SET_APPLICATION_LOADING = 'SET_APPLICATION_LOADING'
export const SUBMIT_APPLICATION = 'SUBMIT_APPLICATION'
export const SUBMIT_APPLICATION_SUCCESS = 'SUBMIT_APPLICATION_SUCCESS'
export const SUBMIT_APPLICATION_FAILURE = 'SUBMIT_APPLICATION_FAILURE'
